# Generated by Django 4.0.6 on 2022-07-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_labels_memos_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='memos', to='app.labels'),
        ),
    ]
