# Generated by Django 4.0.6 on 2022-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_memos_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
